#!/usr/bin/env python3
"""Turn the reference recording's contour into an ESPHome step table.

We do not play the recording. We measure its pitch and amplitude over time,
transpose the pitch up into the buzzer's usable band, and replay that contour
as a PWM tone. The gesture is the real one; the timbre is whatever the buzzer
can manage.

Run analyse_ref.py first; it writes ref_contour.npz, which this reads.
"""
import numpy as np
from scipy import signal

T_START, T_END = 0.32, 3.56     # the sounding part of the reference
TARGET_TAIL_HZ = 800.0          # where the final note should land
MAX_LEVEL = 0.62                # PWM duty swing, matching the other cues
STEP_MS = 12                    # contour step length, replayed by pwm_speech


def build():
    d = np.load("ref_contour.npz")
    t, f, e = d["t"], d["f"], d["e"]

    # median-filter the pitch track, then interpolate across unvoiced frames
    voiced = f > 0
    fs = f.copy()
    fs[voiced] = signal.medfilt(f[voiced], 5)
    idx = np.arange(len(fs))
    fs = np.interp(idx, idx[voiced], fs[voiced])

    # scale so the final sustained note sits on the target
    tail = (t > 2.5) & (t < 3.3) & voiced
    scale = TARGET_TAIL_HZ / float(np.median(f[tail]))

    # resample both contours onto the 12 ms step grid
    n_steps = int((T_END - T_START) * 1000 / STEP_MS)
    grid = T_START + np.arange(n_steps) * STEP_MS / 1000.0
    freq = np.interp(grid, t, fs) * scale
    lvl = np.interp(grid, t, e) * MAX_LEVEL
    lvl[lvl < 0.03] = 0.0                       # gaps between the wahs

    print(f"scale x{scale:.3f}   steps {n_steps}   "
          f"duration {n_steps*STEP_MS/1000:.2f}s")
    return freq, lvl, scale


def emit_header(freq, lvl, path="../components/pwm_speech/contour_data.h"):
    """Write the contour table that pwm_speech replays (sound: trombone)."""
    fi = np.clip(np.round(freq), 0, 65535).astype(int)
    li = np.clip(np.round(lvl / MAX_LEVEL * 255), 0, 255).astype(int)
    lines = ["// Generated by audio/build_from_ref.py - do not hand-edit.",
             "// Tone contours for pwm_speech: a frequency (Hz) and a level (0-255) per",
             "// fixed-length step, replayed by PwmSpeech::loop() without blocking.",
             "#pragma once",
             "",
             "#include <cstdint>",
             "",
             "namespace esphome {",
             "namespace pwm_speech {",
             "",
             "// \"trombone\" - sad trombone, measured from audio/reference.mp3 and",
             f"// transposed so the sustained final note lands on {TARGET_TAIL_HZ:.0f} Hz.",
             f"// {len(fi)} steps of {STEP_MS} ms = {len(fi)*STEP_MS/1000:.2f} s",
             "",
             "static const uint16_t TROMBONE_F[] = {"]
    for i in range(0, len(fi), 12):
        lines.append("    " + ",".join(f"{v:5d}" for v in fi[i:i+12]) + ",")
    lines += ["};", "",
              "static const uint8_t TROMBONE_L[] = {"]
    for i in range(0, len(li), 16):
        lines.append("    " + ",".join(f"{v:3d}" for v in li[i:i+16]) + ",")
    lines += ["};", "",
              f"static const uint16_t TROMBONE_STEPS = {len(fi)};",
              "",
              "struct Contour {",
              "  const uint16_t *freq;",
              "  const uint8_t *level;",
              "  uint16_t steps;",
              "  uint16_t step_ms;",
              "};",
              "",
              "// Order must match CONTOURS in __init__.py.",
              "static const Contour CONTOURS[] = {",
              f"    {{TROMBONE_F, TROMBONE_L, TROMBONE_STEPS, {STEP_MS}}},",
              "};",
              "",
              "static const uint8_t CONTOUR_COUNT = 1;",
              "",
              "}  // namespace pwm_speech",
              "}  // namespace esphome"]
    with open(path, "w", newline="\n") as fh:    # LF even on Windows
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {path}  ({len(fi)} steps, {len(fi)*3} bytes)")


if __name__ == "__main__":
    freq, lvl, scale = build()
    emit_header(freq, lvl)
